"use client";
import NavBar from "./components/NavBar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeConfig } from "../themeConfig/theme.config";
import { store } from "../redux/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <ThemeConfig>
            <NavBar />
            {children}
          </ThemeConfig>
        </Provider>
      </body>
    </html>
  );
}
